### ISSUE TITLE
Meteor.bindEnvironment not working as expected when wrapping Neo4j callback

### ISSUE THREAD

**Issue by sunny-g** [sunny-g/whuffie#14]
**Background:**
When a user submits a trustSet transaction, we change the relationship metadata for that particular edge in Neo4j, then upon success, store the transaction metadata in a Transactions collection in Mongo. The relevant Neo4j function is ```upsertEdge``` and is found [here](https://github.com/sunny-g/whuffie/blob/master/server/db/neoOperations.js#L33). The Mongo function to run in the callback is defined as ```insertTransaction``` and is found [here](https://github.com/sunny-g/whuffie/blob/master/server/db/mongoOperations.js#L8). Together they are used [here](https://github.com/sunny-g/whuffie/blob/master/server/processor/handlers/handlers.js#L24).

**Problem:**
I am unable to just wrap the [callback](https://github.com/sunny-g/whuffie/blob/master/server/db/neoOperations.js#L49) in ```Meteor.bindEnvironment``` instead of the fiber, and here's the error I get when I don't use the Fiber:
```
W20150627-14:56:00.847(-7)? (STDERR) /Users/sunnygonnabathula/gitdev/wufi/.meteor/local/build/programs/server/packages/meteor.js:942
W20150627-14:56:00.850(-7)? (STDERR)     throw new Error("Meteor code must always run within a Fiber. " +          
W20150627-14:56:00.850(-7)? (STDERR)           ^
W20150627-14:56:00.866(-7)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20150627-14:56:00.867(-7)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20150627-14:56:00.867(-7)? (STDERR)     at Object.Meteor.bindEnvironment (packages/meteor/dynamics_nodejs.js:85:1)
W20150627-14:56:00.867(-7)? (STDERR)     at Object.messageHandler.trustHandler (app/server/processor/handlers/handlers.js:26:14)
W20150627-14:56:00.867(-7)? (STDERR)     at WebSocket.timeout (app/server/processor/processor.js:45:20)
W20150627-14:56:00.867(-7)? (STDERR)     at WebSocket.emit (events.js:98:17)
W20150627-14:56:00.867(-7)? (STDERR)     at Receiver.ontext (/Users/sunnygonnabathula/gitdev/wufi/.meteor/local/isopacks/npm-container/npm/node_modules/ws/lib/WebSocket.js:798:10)
W20150627-14:56:00.867(-7)? (STDERR)     at /Users/sunnygonnabathula/gitdev/wufi/.meteor/local/isopacks/npm-container/npm/node_modules/ws/lib/Receiver.js:473:18
W20150627-14:56:00.867(-7)? (STDERR)     at Receiver.applyExtensions (/Users/sunnygonnabathula/gitdev/wufi/.meteor/local/isopacks/npm-container/npm/node_modules/ws/lib/Receiver.js:360:5)
W20150627-14:56:00.868(-7)? (STDERR)     at /Users/sunnygonnabathula/gitdev/wufi/.meteor/local/isopacks/npm-container/npm/node_modules/ws/lib/Receiver.js:462:14
W20150627-14:56:00.868(-7)? (STDERR)     at Receiver.flush (/Users/sunnygonnabathula/gitdev/wufi/.meteor/local/isopacks/npm-container/npm/node_modules/ws/lib/Receiver.js:336:3)
=> Exited with code: 8
```

**Comment by dr-dimitru** [comment]
Hello @sunny-g ,
It looks like you've mixed `neo4jReactivity` and `neo4jDriver` packages functionality
Please try to use only reactive package, and switch to [collection/publish/subscribe methodology](https://github.com/VeliovGroup/ostrio-Neo4jreactivity#as-collection-and-publishsubscribe)

**Comment by sunny-g** [comment]
Hey @dr-dimitru , how would I set up a a purely server-side method if I shouldn't use ```N4JDB.query```?

**Comment by dr-dimitru** [comment]
@sunny-g `Meteor.neo4j.query()` is isomorphic, - try to use it
